<?xml version="1.0" encoding="utf-8"?><Database Name="db25fa972d13ee46be84e5a1d200e1e4a8" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=25fa972d-13ee-46be-84e5-a1d200e1e4a8.sqlserver.sequelizer.com;Initial Catalog=db25fa972d13ee46be84e5a1d200e1e4a8;Persist Security Info=True;User ID=pappkebdjsggdhkc" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="db25fa972d13ee46be84e5a1d200e1e4a8ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Teacher" Member="Teachers">
    <Type Name="Teacher">
      <Column Name="ID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sex" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Academic" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="ID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sex" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Academic" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Major" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Grade" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Grade" Member="Grades">
    <Type Name="Grade">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Grade" Member="Grade1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Major" Member="Majors">
    <Type Name="Major">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Major" Member="Major1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Mark" Member="Marks">
    <Type Name="Mark">
      <Column Name="ID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ThesisMark" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SpeechMark" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalMark" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ThesisCheck" Member="ThesisChecks">
    <Type Name="ThesisCheck">
      <Column Name="ID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Topic" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Literature" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ResearchCapacity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThesisQuality" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InnovationCapacity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ThesisTopic" Member="ThesisTopics">
    <Type Name="ThesisTopic">
      <Column Name="ID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Thesistopic" Member="Thesistopic1" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>